version: "3.8"
services:
  frontend:
    image: biab-frontend
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - mern-network  # Define the network for the frontend service
  backend:
    image: biab-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql  # This makes biab-backend dependent on the MySQL service
    networks:
      - mern-network  # Define the network for the backend service
  mysql:
    image: biab-mysql  # Change this line to use the "biab-mysql" image
    environment:
      MYSQL_ROOT_PASSWORD: Sairam@123
      MYSQL_DATABASE: biab
      MYSQL_USER: root
      MYSQL_PASSWORD: Sairam@123
    ports:
      - "3004:3004"  # Map the MySQL port to the host if needed
    networks:
      - mern-network  # Define the network for the MySQL service
volumes:
  mysql-data:  # Define a volume for MySQL data persistence
networks:
  mern-network:
    driver: bridge
