version: '3.8'

services:
  biab-frontend:
    image: frontend
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - biab-network
    depends_on:
      - biab-backend

  biab-backend:
    image: backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - biab-network
    depends_on:
      - biab-mongodb
      - biab-mysql

  biab-mongodb:  # Add a MongoDB service
    image: mongo
    restart: unless-stopped
    ports:
      - "27018:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tvast
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ps
    volumes:
     - "/var/lib/mongodb-back:/data/db"
    networks:
      - biab-network
    
  biab-mysql:  # MySQL service
    image: biab_users
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=Sairam@123
      - MYSQL_DATABASE=users
    networks:
      - biab-network

networks:
  biab-network:
    driver: bridge
